[profile.dev]
opt-level = 0

[profile.release]
lto = "fat"
opt-level = 3
codegen-units = 1
panic = "abort"

[profile.bench]
lto = "fat"
opt-level = 3
codegen-units = 1

[workspace]
resolver = "2"
members = [
  "crates/derive-redis-swapplex",
  "crates/redis-swapplex",
]
