[package]
name = "redis-swapplex"
authors = ["Thomas Sieverding <Thomas@bajix.com>"]
version = "0.4.1"
edition = "2021"
description = "Atomic state-transition based Redis multiplexing with reconnection notifications"
readme = "../../README.md"
license = "MIT"
repository = "https://github.com/Bajix/redis-swapplex/"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arc-swap = "1.6.0"
derive-redis-swapplex = { version  = "0.4.1", path = "../derive-redis-swapplex"}
env-url = "2.0.3"
futures-util = "0.3"
once_cell = "1.17"
redis = { version = "0.22", features = ["aio", "tokio-comp"] }
tokio = { version = "1", features =  ["sync", "parking_lot"] }

[dev-dependencies]
criterion = { version = "0.4.0", features = ["async_tokio", "html_reports"] }
ctor = "0.1.26"
redis = { version = "0.22", features = ["connection-manager"]}
tokio = { version = "1", features =  ["rt", "macros", "time", "rt-multi-thread"] }
fred = "5.2.0"

[[bench]]
name = "benchmarks"
path = "../../benches/bench.rs"
harness = false
doc = false
