[package]
name = "redis-swapplex"
authors = ["Thomas Sieverding <Thomas@bajix.com>"]
version = "0.3.0"
edition = "2021"
description = "Atomic state-transition based Redis multiplexing with reconnection notifications"
readme = "../../README.md"
license = "MIT"
repository = "https://github.com/Bajix/redis-swapplex/"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arc-swap = "1.5"
derive-redis-swapplex = { version  = "0.2.0", path = "../derive-redis-swapplex"}
env-url = "2.0.3"
futures-util = "0.3"
once_cell = "1.14"
redis = { version = "0.21", features = ["aio", "tokio-comp"] }
tokio = { version = "1", features =  ["sync", "parking_lot"] }

[dev-dependencies]
tokio = { version = "1", features =  ["rt", "macros"] }
ctor = "0.1.23"
